---
title: "About me"
output: 
  html_document:
    toc: FALSE
---


##Background


![pic.jpg]C:\Users\Priyanka\Desktop\MADA_2021\

My name is Priyanka Gannavarapu. I graduated  with a M.S in Drug Regulatory affairs from the Long island university,NY in 2019.I am into my second year of Ph.D.in Pharmaceutical Health Services, Outcomes, and Policy from the College of Pharmacy.

##Statistical Experience and Research interests

I am pretty new to the world of statistics . Till now, I have worked on jmp , STATA and a little SPSS. I have been using STATA for a project that i have been working on.

My research focus is on health behavior models which help us to explain why individuals and communities behave the way they do.


##Fun Facts

I am a trained Indian classical singer.
True crime buff and love Agatha Christie's
love baking.


##What I Hope to Learn in this Course

I would describe myself as a beginner using R and Github. i hope to get proficient in R and also machine learing

##5 Weird and Hilarious Uses of Data Science

{https://www.analyticsvidhya.com/blog/2019/12/five-weird-data-science-uses/}

