---
title: "Tidy Tuesday2"
author: "priyanka"
date: "11/11/2021"
output: html_document
---

```{r}
library(schrute)
library(tidyverse)
library(tidymodels)
```

```{r}
tibble(theoffice)

office_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv')


office_ratings


remove_regex <- "[:punct:]|[:digit:]|parts |part |the |and"
```

```{r}
office_ratings %>%
  group_by(season) %>%
  summarise(avg_rating = mean(imdb_rating)) %>%
  ggplot(aes(season, avg_rating)) +
  geom_line() +
  scale_x_continuous(breaks = 1:9)
```

```{r}
raw_ratings <- office_ratings %>%
     mutate(
         episode_name = title,
       episode_name = episode_name,
         episode_name = episode_name,
         imdb_rating
     )
```

```{r}
office_info <- schrute::theoffice %>%
  mutate(
    season = as.numeric(season),
    episode = as.numeric(episode),
    episode_name = str_to_lower(episode_name),
    episode_name = str_remove_all(episode_name, remove_regex),
    episode_name = str_trim(episode_name)
  ) %>%
  select(season, episode, episode_name, director, writer, character)
```



```{r}
characters <- office_info %>%
  count(episode_name, character) %>%
  add_count(character, wt = n, name = "character_count") %>%
  filter(character_count > 800) %>%
  select(-character_count) %>%
  pivot_wider(
    names_from = character,
    values_from = n,
    values_fill = list(n = 0)
  )
```

```{r}
creators <- office_info %>%
  distinct(episode_name, director, writer) %>%
  pivot_longer(director:writer, names_to = "role", values_to = "person") %>%
  separate_rows(person, sep = ";") %>%
  add_count(person) %>%
  filter(n > 20) %>%
  distinct(episode_name, person) %>%
  mutate(person_value = 1) %>%
  pivot_wider(
    names_from = person,
    values_from = person_value,
    values_fill = list(person_value = 0)
  )
```


```{r}
office <- office_info %>%
   distinct(season, episode, episode_name) %>%
   inner_join(characters) %>%
     inner_join(creators) %>%
     inner_join(raw_ratings %>%
                    select(episode_name, imdb_rating))
```

```{r}
raw_ratings %>%
  group_by(season) %>%
  summarise(avg_rating = mean(imdb_rating)) %>%
  ggplot(aes(season, avg_rating)) +
  geom_line() +
  scale_x_continuous(breaks = 1:9)
```

```{r}
raw_ratings %>%
           arrange(desc(imdb_rating))%>%
           mutate(title = paste0(season,".", episode," ",title),
                                                     title = fct_reorder(title, imdb_rating)) %>%
              head(20)%>%
     ggplot(aes(title, imdb_rating, color = factor(season))) +
         geom_point() + coord_flip()

```





```{r}
office_split <- initial_split(office, strata = season)
office_train <- training(office_split)
office_test <- testing(office_split)





set.seed(123)
 
folds <- vfold_cv(office_train, v = 5, repeats =5, strata = season)

office_rec <- recipe(season ~ ., data = office_train)

lm_mod <- 
    linear_reg() %>% set_engine("lm")
    
rec.null <- recipes::recipe(season ~ 1 , data = office_train)


null_workflow <-
     workflow() %>% 
    add_model(lm_mod) %>% 
     add_recipe(rec.null)
     
null_fit<-
       null_workflow %>%
         fit(data = office_train)

null_fit %>%
     extract_fit_parsnip() %>% 
     tidy()

predict(null_fit, office_test)


null_test_aug <- augment(null_fit, office_test)

 rmse_null_test <- null_test_aug %>% 
     rmse(truth = imdb_rating, .pred)
 
 
 predict(null_fit, office_train)
 
 
 null_train_aug <- 
    augment(null_fit, office_train) 
 
 rmse_null_train <- null_train_aug %>% 
    rmse(truth = imdb_rating, .pred) 
 
rmse_null_test


tree_spec <- 
     decision_tree(
        cost_complexity = tune(),
         tree_depth = tune(),
        min_n = tune()
     ) %>% 
    set_engine("rpart") %>% 
    set_mode("regression")

tree_wf <- workflow() %>% 
     add_model(tree_spec) %>% 
    add_recipe(office_rec)
 tree_grid <- grid_latin_hypercube(
     cost_complexity(), tree_depth(), min_n(), size = 10
 )

tree_res <- tree_wf %>%
   tune::tune_grid(resamples = folds,
                     grid = tree_grid,
                     control = control_grid(verbose = FALSE, save_pred = TRUE),                                    metrics = metric_set(rmse))

 tree_res %>% 
     collect_metrics() 
 
 
 tree_res %>% autoplot()
 
 
tree_res %>%
    show_best("rmse") 

best_tree <- tree_res %>%
     select_best("rmse")

best_tree


final_wf <- 
tree_wf %>% 
    finalize_workflow(best_tree)

 final_wf
 
 
 final_fit <- 
    final_wf %>%
     last_fit(office_split)
 
 final_fit %>%
     collect_metrics()

```


```{r}

office_split <- initial_split(office,prop = 3/4, strata = season)

office_train <- training(office_split)
 
office_test <- testing(office_split)



office_rec <- recipe(season ~ ., data = office_train) %>%
  update_role(episode_name, new_role = "ID") %>%
  step_zv(all_numeric(), -all_outcomes()) %>%
  step_normalize(all_numeric(), -all_outcomes())

office_prep <- office_rec %>%
  prep(strings_as_factors = FALSE)


## LASSO Model

# model specification


lasso_mod <- 
  linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")
```

# Create a workflow


#Workflow
```{r}
lasso_workflow <-
  workflow() %>%
  add_model(lasso_mod) %>%
  add_recipe(office_rec)
```

```{r}
lasso_mod <- 
  linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")
```

##Tuning

```{r}
lasso_grid <- tibble(penalty = 10^seq(-4,-1,length.out = 30))


lasso_res <-
    lasso_workflow %>%
     tune_grid(folds,
grid = lasso_grid,
               control = 
                   control_grid(save_pred = TRUE),
              metrics = 
                   metric_set(rmse))



 lasso_res
 
 
 
 best_model <- lasso_res %>%
    show_best("rmse", n = 15) %>%
    arrange(penalty)
 
 
best_model 
```











